cargo-features = ["codegen-backend"]

[package]
name = "rayon-serde-data"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.197"
serde_json = "1.0.115"

[profile.dev]
codegen-backend = "cranelift"
